  config:
    kmls:  # optional KML files that specify geographic regions.  aircraft may be in 0-1 regions per file at any time
      - tests/test1.kml 

  aircraft_lists:
    # optional lists of tail numbers of interest.
    alert_aircraft: [ "N12345" ] 

  rules:
    arbitrary_rulename:
      conditions: 
        # when should we trigger this rule?  AND expression -- all conditions must be met.
        min_alt: 4000        # feet MSL, must be >= to match
        max_alt: 10000       # feel MSL, must be <= to match
        aircraft_list: alert_aircraft  # use aircraft_list above
        regions: [ "23 upwind", "Pattern" ]  # will match if inside any of these KML polygons
        regions: []          # not in any KML-defined region
        transition_regions: [ "from", "to" ] # moved from first region to second
        latlongring: [20, 40.763537, -119.2122323] # nm, lat, long
        proximity: [400, .3] # alt separation in feet, lateral separation in nm
        cooldown: 1          # minutes to wait before matching again
        has_attr: wd         # last report has a json element matching the string
        min_time: 400        # earliest time, in 24h format, but don't use leading 0's
        max_time: 1600       # latest time, in 24h format, but don't use leading 0's
      actions:
        # what should we do when triggered?
        callback: ground_cb  # call a function as specified by AdsbActions.register_callback()
        expire_callback: expire_cb  # callback for when the flight is being evicted
        webhook: True        # slack etc
        print: True          # print info about this aircraft to console
        note: "text flag"    # apply this note to aircraft, for use in later callbacks
        note: ~              # clear note
        track: True          # track execution statistics for this rule, to be printed later

# Other notes:
# - Callbacks take one arg (the flight) unless matching on a proximity condition -- in that
#   case they take 2 (the two nearby flights)
# - want an unconditional rule?  use "conditions: []"
# - "None" is not valid in yaml, use ~ instead