name = "request-api"
main = "src/index.js"
compatibility_date = "2024-01-01"
account_id = "3b1da983787f30212a09b82fece98f35"

routes = [
  { pattern = "airbornehotspots.org/request", zone_name = "airbornehotspots.org" },
  { pattern = "airbornehotspots.com/request", zone_name = "airbornehotspots.com" },
  { pattern = "airbornehotspots.org/subscribe", zone_name = "airbornehotspots.org" },
  { pattern = "airbornehotspots.com/subscribe", zone_name = "airbornehotspots.com" }
]

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "hotspots"
